export default function sitemap() {
  return [
    {
      url: 'https://www.calculatecgpa.com',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
      alternates: {
        languages: {
          en: 'https://calculatecgpa.com/',
          'en-US': 'https://calculatecgpa.com/grade-calculator/us',
          'en-GB': 'https://calculatecgpa.com/grade-calculator/uk',
          'en-NZ': 'https://calculatecgpa.com/grade-calculator/nz',
          'de-CH': 'https://calculatecgpa.com/grade-calculator/ch',
          'de-DE': 'https://calculatecgpa.com/grade-calculator/germany',
          'nl-NL': 'https://calculatecgpa.com/grade-calculator/nl',
        },
      },
    },
    {
      url: 'https://www.calculatecgpa.com/grade-calculator/us',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
      alternates: {
        languages: {
          en: 'https://calculatecgpa.com/',
          'en-US': 'https://calculatecgpa.com/grade-calculator/us',
          'en-GB': 'https://calculatecgpa.com/grade-calculator/uk',
          'en-NZ': 'https://calculatecgpa.com/grade-calculator/nz',
          'de-CH': 'https://calculatecgpa.com/grade-calculator/ch',
          'de-DE': 'https://calculatecgpa.com/grade-calculator/germany',
          'nl-NL': 'https://calculatecgpa.com/grade-calculator/nl',
        },
      },
    },
    {
      url: 'https://www.calculatecgpa.com/grade-calculator/uk',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
      alternates: {
        languages: {
          en: 'https://calculatecgpa.com/',
          'en-US': 'https://calculatecgpa.com/grade-calculator/us',
          'en-GB': 'https://calculatecgpa.com/grade-calculator/uk',
          'en-NZ': 'https://calculatecgpa.com/grade-calculator/nz',
          'de-CH': 'https://calculatecgpa.com/grade-calculator/ch',
          'de-DE': 'https://calculatecgpa.com/grade-calculator/germany',
          'nl-NL': 'https://calculatecgpa.com/grade-calculator/nl',
        },
      },
    },
    {
      url: 'https://www.calculatecgpa.com/grade-calculator/nz',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
      alternates: {
        languages: {
          en: 'https://calculatecgpa.com/',
          'en-US': 'https://calculatecgpa.com/grade-calculator/us',
          'en-GB': 'https://calculatecgpa.com/grade-calculator/uk',
          'en-NZ': 'https://calculatecgpa.com/grade-calculator/nz',
          'de-CH': 'https://calculatecgpa.com/grade-calculator/ch',
          'de-DE': 'https://calculatecgpa.com/grade-calculator/germany',
          'nl-NL': 'https://calculatecgpa.com/grade-calculator/nl',
        },
      },
    },
    {
      url: 'https://www.calculatecgpa.com/grade-calculator/ch',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
      alternates: {
        languages: {
          en: 'https://calculatecgpa.com/',
          'en-US': 'https://calculatecgpa.com/grade-calculator/us',
          'en-GB': 'https://calculatecgpa.com/grade-calculator/uk',
          'en-NZ': 'https://calculatecgpa.com/grade-calculator/nz',
          'de-CH': 'https://calculatecgpa.com/grade-calculator/ch',
          'de-DE': 'https://calculatecgpa.com/grade-calculator/germany',
          'nl-NL': 'https://calculatecgpa.com/grade-calculator/nl',
        },
      },
    },
    {
      url: 'https://www.calculatecgpa.com/grade-calculator/nl',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
      alternates: {
        languages: {
          en: 'https://calculatecgpa.com/',
          'en-US': 'https://calculatecgpa.com/grade-calculator/us',
          'en-GB': 'https://calculatecgpa.com/grade-calculator/uk',
          'en-NZ': 'https://calculatecgpa.com/grade-calculator/nz',
          'de-CH': 'https://calculatecgpa.com/grade-calculator/ch',
          'de-DE': 'https://calculatecgpa.com/grade-calculator/germany',
          'nl-NL': 'https://calculatecgpa.com/grade-calculator/nl',
        },
      },
    },
    {
      url: 'https://www.calculatecgpa.com/grade-calculator/germany',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
      alternates: {
        languages: {
          en: 'https://calculatecgpa.com/',
          'en-US': 'https://calculatecgpa.com/grade-calculator/us',
          'en-GB': 'https://calculatecgpa.com/grade-calculator/uk',
          'en-NZ': 'https://calculatecgpa.com/grade-calculator/nz',
          'de-CH': 'https://calculatecgpa.com/grade-calculator/ch',
          'de-DE': 'https://calculatecgpa.com/grade-calculator/germany',
          'nl-NL': 'https://calculatecgpa.com/grade-calculator/nl',
        },
      },
    },
    {
      url: 'https://www.calculatecgpa.com/blooket-simulator',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: 'https://www.calculatecgpa.com/blooket/all-blooks',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: 'https://www.calculatecgpa.com/blooket/blooket-pack-calculator',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: 'https://www.calculatecgpa.com/grade-calculator/cgpa-percentage',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://calculatecgpa.com/grade-calculator/cgpa-to-gpa',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: 'https://www.calculatecgpa.com/about-us',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.5,
    },
    {
      url: 'https://www.calculatecgpa.com/contact-us',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.5,
    },
    {
      url: 'https://www.calculatecgpa.com/privacy-policy',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
  ];
}
