export const packsData = {
  packs: [
    {
      packId: 'autumn',
      name: 'Autumn Pack',
      costTokens: 25,
      poster: '/assets/blooket/packs/autumnpack.webp',
      blooks: [
        {
          name: 'Black Bear',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/autumn/blackbear.svg',
        },
        {
          name: 'Pumpkin Pie',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/autumn/pumpkinpie.svg',
        },
        {
          name: 'Chipmunk',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/autumn/chipmunk.svg',
        },
        {
          name: 'Cornucopia',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/autumn/cornucopia.svg',
        },
        {
          name: 'Autumn Cat',
          rarity: 'Rare',
          dropRatePct: 6,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/autumn/autumncat.svg',
        },
        {
          name: 'Pumpkin Puppy',
          rarity: 'Rare',
          dropRatePct: 6,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/autumn/pumpkinpuppy.svg',
        },
        {
          name: 'Red Squirrel',
          rarity: 'Rare',
          dropRatePct: 6,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/autumn/redsquirrel.svg',
        },
        {
          name: 'Autumn Crow',
          rarity: 'Epic',
          dropRatePct: 2.95,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/autumn/autumncrow.svg',
        },
        {
          name: 'Turkey',
          rarity: 'Legendary',
          dropRatePct: 1.0,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/autumn/turkey.svg',
        },
        {
          name: 'Gold Finch',
          rarity: 'Chroma',
          dropRatePct: 0.05,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/autumn/goldfinch.svg',
        },
      ],
    },
    {
      packId: 'lunch',
      name: 'Lunch Pack',
      costTokens: 25,
      poster: '/assets/blooket/packs/lunchpack.webp',
      blooks: [
        {
          name: 'Banana',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/lunch/bananas.svg',
        },
        {
          name: 'Watermelon',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/lunch/watermelon.svg',
        },
        {
          name: 'Cheese',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/lunch/cheese.svg',
        },
        {
          name: 'Doughnut',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/lunch/doughnut.svg',
        },
        {
          name: 'Taco',
          rarity: 'Rare',
          dropRatePct: 7.0,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/lunch/taco.svg',
        },
        {
          name: 'Bao',
          rarity: 'Rare',
          dropRatePct: 7.0,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/lunch/bao.svg',
        },
        {
          name: 'Sushi',
          rarity: 'Rare',
          dropRatePct: 7.0,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/lunch/sushi.svg',
        },
        {
          name: 'Cheeseburger',
          rarity: 'Epic',
          dropRatePct: 3.31,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/lunch/cheeseburger.svg',
        },
        {
          name: 'Sandwich',
          rarity: 'Legendary',
          dropRatePct: 0.65,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/lunch/sandwich.svg',
        },
        {
          name: 'Half a Sandwich',
          rarity: 'Chroma',
          dropRatePct: 0.04,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/lunch/halfasandwich.svg',
        },
      ],
    },
    {
      packId: 'bug',
      name: 'Bug Pack',
      costTokens: 25,
      poster: '/assets/blooket/packs/bugpack.webp',
      blooks: [
        {
          name: 'Ant',
          rarity: 'Uncommon',
          dropRatePct: 19.625,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/bug/ant.svg',
        },
        {
          name: 'Rhino Beetle',
          rarity: 'Uncommon',
          dropRatePct: 19.625,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/bug/rhinobeetle.svg',
        },
        {
          name: 'Ladybug',
          rarity: 'Uncommon',
          dropRatePct: 19.625,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/bug/ladybug.svg',
        },
        {
          name: 'Fly',
          rarity: 'Uncommon',
          dropRatePct: 19.625,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/bug/fly.svg',
        },
        {
          name: 'Worm',
          rarity: 'Rare',
          dropRatePct: 9.0,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/bug/worm.svg',
        },
        {
          name: 'Bee',
          rarity: 'Rare',
          dropRatePct: 9.0,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/bug/bee.svg',
        },
        {
          name: 'Mantis',
          rarity: 'Epic',
          dropRatePct: 2.97,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/bug/mantis.svg',
        },
        {
          name: 'Butterfly',
          rarity: 'Legendary',
          dropRatePct: 0.5,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/bug/butterfly.svg',
        },
        {
          name: 'Blue Butterfly',
          rarity: 'Chroma',
          dropRatePct: 0.03,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/bug/bluebutterfly.svg',
        },
      ],
    },
    {
      packId: 'pirate',
      name: 'Pirate Pack',
      costTokens: 25,
      poster: '/assets/blooket/packs/piratepack.webp',
      blooks: [
        {
          name: 'Deckhand',
          rarity: 'Uncommon',
          dropRatePct: 16,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/pirate/deckhand.svg',
        },
        {
          name: 'Buccaneer',
          rarity: 'Uncommon',
          dropRatePct: 16.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/pirate/buccaneer.svg',
        },
        {
          name: 'Swashbuckler',
          rarity: 'Uncommon',
          dropRatePct: 16.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/pirate/swashbuckler.svg',
        },
        {
          name: 'Treasure Map',
          rarity: 'Uncommon',
          dropRatePct: 16.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/pirate/treasuremap.svg',
        },
        {
          name: 'Seagull',
          rarity: 'Uncommon',
          dropRatePct: 16.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/pirate/seagull.svg',
        },
        {
          name: 'Jolly Pirate',
          rarity: 'Rare',
          dropRatePct: 8,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/pirate/jollypirate.svg',
        },
        {
          name: 'Pirate Ship',
          rarity: 'Rare',
          dropRatePct: 8,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/pirate/pirateship.svg',
        },
        {
          name: 'Kraken',
          rarity: 'Epic',
          dropRatePct: 3.67,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/pirate/kraken.svg',
        },
        {
          name: 'Captain Blackbeard',
          rarity: 'Legendary',
          dropRatePct: 0.3,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/pirate/captainblackbeard.svg',
        },
        {
          name: 'Pirate Pufferfish',
          rarity: 'Chroma',
          dropRatePct: 0.03,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/pirate/piratepufferfish.svg',
        },
      ],
    },
    {
      packId: 'outback',
      name: 'Outback Pack',
      costTokens: 25,
      poster: '/assets/blooket/packs/outbackpack.webp',
      blooks: [
        {
          name: 'Dingo',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/outback/dingo.svg',
        },
        {
          name: 'Echidna',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/outback/echidna.svg',
        },
        {
          name: 'Koala',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/outback/koala.svg',
        },
        {
          name: 'Kookaburra',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/outback/kookaburra.svg',
        },
        {
          name: 'Platypus',
          rarity: 'Rare',
          dropRatePct: 7,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/outback/platypus.svg',
        },
        {
          name: 'Joey',
          rarity: 'Rare',
          dropRatePct: 7,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/outback/joey.svg',
        },
        {
          name: 'Kangaroo',
          rarity: 'Rare',
          dropRatePct: 7,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/outback/kangaroo.svg',
        },
        {
          name: 'Crocodile',
          rarity: 'Epic',
          dropRatePct: 3.6,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/outback/crocodile.svg',
        },
        {
          name: 'Sugar Glider',
          rarity: 'Legendary',
          dropRatePct: 0.37,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/outback/sugarglider.svg',
        },
        {
          name: 'Teal Platypus',
          rarity: 'Chroma',
          dropRatePct: 0.03,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/outback/tealplatypus.svg',
        },
      ],
    },
    {
      packId: 'ice',
      name: 'Ice Monster Pack',
      costTokens: 25,
      poster: '/assets/blooket/packs/icepack.webp',
      blooks: [
        {
          name: 'Ice Bat',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/ice/icebat.svg',
        },
        {
          name: 'Ice Bug',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/ice/icebug.svg',
        },
        {
          name: 'Ice Elemental',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/ice/iceelemental.svg',
        },
        {
          name: 'Rock Monster',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/ice/rockmonster.svg',
        },
        {
          name: 'Dink',
          rarity: 'Rare',
          dropRatePct: 8.5,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/ice/dink.svg',
        },
        {
          name: 'Donk',
          rarity: 'Rare',
          dropRatePct: 8.5,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/ice/donk.svg',
        },
        {
          name: 'Bush Monster',
          rarity: 'Epic',
          dropRatePct: 4.5,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/ice/bushmonster.svg',
        },
        {
          name: 'Yeti',
          rarity: 'Legendary',
          dropRatePct: 0.35,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/ice/yeti.svg',
        },
        {
          name: 'Ice Slime',
          rarity: 'Chroma',
          dropRatePct: 0.08,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/ice/iceslime.svg',
        },
        {
          name: 'Frozen Fossil',
          rarity: 'Chroma',
          dropRatePct: 0.05,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/ice/frozenfossil.svg',
        },
        {
          name: 'Ice Crab',
          rarity: 'Chroma',
          dropRatePct: 0.02,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/ice/icecrab.svg',
        },
      ],
    },
    {
      packId: 'dino',
      name: 'Dino Pack',
      costTokens: 25,
      poster: '/assets/blooket/packs/dinopack.webp',
      blooks: [
        {
          name: 'Amber',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/dino/amber.svg',
        },
        {
          name: 'Dino Egg',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/dino/dinoegg.svg',
        },
        {
          name: 'Dino Fossil',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/dino/dinofossil.svg',
        },
        {
          name: 'Stegosaurus',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/dino/stegosaurus.svg',
        },
        {
          name: 'Velociraptor',
          rarity: 'Rare',
          dropRatePct: 9,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/dino/velociraptor.svg',
        },
        {
          name: 'Brontosaurus',
          rarity: 'Rare',
          dropRatePct: 9,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/dino/brontosaurus.svg',
        },
        {
          name: 'Triceratops',
          rarity: 'Epic',
          dropRatePct: 3.72,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/dino/triceratops.svg',
        },
        {
          name: 'Tyrannosaurus Rex',
          rarity: 'Legendary',
          dropRatePct: 0.3,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/dino/tyrannosaurusrex.svg',
        },
      ],
    },
    {
      packId: 'safari',
      name: 'Safari Pack',
      costTokens: 20,
      poster: '/assets/blooket/packs/safaripack.webp',
      blooks: [
        {
          name: 'Panda',
          rarity: 'Uncommon',
          dropRatePct: 15.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/safari/panda.svg',
        },
        {
          name: 'Sloth',
          rarity: 'Uncommon',
          dropRatePct: 15.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/safari/sloth.svg',
        },
        {
          name: 'Tenrec',
          rarity: 'Uncommon',
          dropRatePct: 15.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/safari/tenrec.svg',
        },
        {
          name: 'Flamingo',
          rarity: 'Uncommon',
          dropRatePct: 15.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/safari/flamingo.svg',
        },
        {
          name: 'Zebra',
          rarity: 'Uncommon',
          dropRatePct: 15.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/safari/zebra.svg',
        },
        {
          name: 'Elephant',
          rarity: 'Rare',
          dropRatePct: 7,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/safari/elephant.svg',
        },
        {
          name: 'Lemur',
          rarity: 'Rare',
          dropRatePct: 7,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/safari/lemur.svg',
        },
        {
          name: 'Peacock',
          rarity: 'Rare',
          dropRatePct: 7,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/safari/peacock.svg',
        },
        {
          name: 'Chameleon',
          rarity: 'Epic',
          dropRatePct: 3.48,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/safari/chameleon.svg',
        },
        {
          name: 'Lion',
          rarity: 'Legendary',
          dropRatePct: 0.5,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/safari/lion.svg',
        },
        {
          name: 'Rainbow Panda',
          rarity: 'Chroma',
          dropRatePct: 0.02,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/safari/rainbowpanda.svg',
        },
      ],
    },
    {
      packId: 'aquatic',
      name: 'Aquatic Pack',
      costTokens: 20,
      poster: '/assets/blooket/packs/aquaticpack.webp',
      blooks: [
        {
          name: 'Old Boot',
          rarity: 'Uncommon',
          dropRatePct: 15.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/aquatic/oldboot.svg',
        },
        {
          name: 'Jellyfish',
          rarity: 'Uncommon',
          dropRatePct: 15.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/aquatic/jellyfish.svg',
        },
        {
          name: 'Clownfish',
          rarity: 'Uncommon',
          dropRatePct: 15.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/aquatic/clownfish.svg',
        },
        {
          name: 'Frog',
          rarity: 'Uncommon',
          dropRatePct: 15.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/aquatic/frog.svg',
        },
        {
          name: 'Crab',
          rarity: 'Uncommon',
          dropRatePct: 15.0,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/aquatic/crab.svg',
        },
        {
          name: 'Pufferfish',
          rarity: 'Rare',
          dropRatePct: 6.1,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/aquatic/pufferfish.svg',
        },
        {
          name: 'Blobfish',
          rarity: 'Rare',
          dropRatePct: 6.1,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/aquatic/blobfish.svg',
        },

        {
          name: 'Octopus',
          rarity: 'Rare',
          dropRatePct: 6.1,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/aquatic/octopus.svg',
        },
        {
          name: 'Narwhal',
          rarity: 'Epic',
          dropRatePct: 3,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/aquatic/narwhal.svg',
        },
        {
          name: 'Dolphin',
          rarity: 'Epic',
          dropRatePct: 3,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/aquatic/dolphin.svg',
        },
        {
          name: 'Baby Shark',
          rarity: 'Legendary',
          dropRatePct: 0.5,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/aquatic/babyshark.svg',
        },

        {
          name: 'Megalodon',
          rarity: 'Legendary',
          dropRatePct: 0.2,
          salePrice: 250,
          blookScore: 35,
          poster: '/assets/blooket/blooks/aquatic/megalodon.svg',
        },
      ],
    },
    {
      packId: 'bot',
      name: 'Bot Pack',
      costTokens: 20,
      poster: '/assets/blooket/packs/botpack.webp',
      blooks: [
        {
          name: 'Lil Bot',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/bot/lilbot.svg',
        },
        {
          name: 'Lovely Bot',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/bot/lovelybot.svg',
        },

        {
          name: 'Angry Bot',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/bot/angrybot.svg',
        },
        {
          name: 'Happy Bot',
          rarity: 'Uncommon',
          dropRatePct: 19.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/bot/happybot.svg',
        },
        {
          name: 'Watson ',
          rarity: 'Rare',
          dropRatePct: 9,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/bot/watson.svg',
        },
        {
          name: 'Buddy Bot',
          rarity: 'Rare',
          dropRatePct: 9,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/bot/buddybot.svg',
        },

        {
          name: 'Brainy Bot',
          rarity: 'Epic',
          dropRatePct: 3.7,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/bot/brainybot.svg',
        },
        {
          name: 'Mega Bot',
          rarity: 'Legendary',
          dropRatePct: 0.3,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/bot/megabot.svg',
        },
      ],
    },
    {
      packId: 'space',
      name: 'Space Pack',
      costTokens: 20,
      poster: '/assets/blooket/packs/spacepack.webp',
      blooks: [
        {
          name: 'Earth',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/space/earth.svg',
        },
        {
          name: 'Meteor',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/space/meteor.svg',
        },
        {
          name: 'Stars',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/space/stars.svg',
        },
        {
          name: 'Alien',
          rarity: 'Uncommon',
          dropRatePct: 18.75,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/space/alien.svg',
        },
        {
          name: 'Planet',
          rarity: 'Rare',
          dropRatePct: 10,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/space/planet.svg',
        },
        {
          name: 'UFO',
          rarity: 'Rare',
          dropRatePct: 10,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/space/ufo.svg',
        },
        {
          name: 'Spaceship',
          rarity: 'Epic',
          dropRatePct: 4.5,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/space/spaceship.svg',
        },

        {
          name: 'Astronaut',
          rarity: 'Legendary',
          dropRatePct: 0.45,
          salePrice: 200,
          blookScore: 75,
          poster: '/assets/blooket/blooks/space/astronaut.svg',
        },
        {
          name: 'Pink Astronaut',
          rarity: 'Chroma',
          dropRatePct: 0.05,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/space/pinkastronaut.svg',
        },
        {
          name: 'Yellow Astronaut',
          rarity: 'Chroma',
          dropRatePct: 0.05,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/space/yellowastronaut.svg',
        },
        {
          name: 'Black Astronaut',
          rarity: 'Chroma',
          dropRatePct: 0.05,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/space/blackastronaut.svg',
        },
        {
          name: 'Orange Astronaut',
          rarity: 'Chroma',
          dropRatePct: 0.05,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/space/orangeastronaut.svg',
        },
        {
          name: 'Red Astronaut',
          rarity: 'Chroma',
          dropRatePct: 0.05,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/space/redastronaut.svg',
        },
        {
          name: 'Brown Astronaut',
          rarity: 'Chroma',
          dropRatePct: 0.05,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/space/brownastronaut.svg',
        },
        {
          name: 'Green Astronaut',
          rarity: 'Chroma',
          dropRatePct: 0.05,
          salePrice: 300,
          blookScore: 50,
          poster: '/assets/blooket/blooks/space/greenastronaut.svg',
        },
      ],
    },
    {
      packId: 'medieval',
      name: 'Medieval Pack',
      poster: '/assets/blooket/packs/medievalpack.webp',
      costTokens: 20,
      blooks: [
        {
          name: 'Witch',
          rarity: 'Uncommon',
          dropRatePct: 13.4,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/medieval/witch.svg',
        },
        {
          name: 'Wizard',
          rarity: 'Uncommon',
          dropRatePct: 13.4,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/medieval/wizard.svg',
        },
        {
          name: 'Elf',
          rarity: 'Uncommon',
          dropRatePct: 13.4,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/medieval/elf.svg',
        },
        {
          name: 'Slime Monster',
          rarity: 'Uncommon',
          dropRatePct: 13.4,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/medieval/slimemonster.svg',
        },
        {
          name: 'Jester',
          rarity: 'Rare',
          dropRatePct: 9,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/medieval/jester.svg',
        },
        {
          name: 'Dragon',
          rarity: 'Rare',
          dropRatePct: 9,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/medieval/dragon.svg',
        },
        {
          name: 'Queen',
          rarity: 'Rare',
          dropRatePct: 9,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/medieval/queen.svg',
        },
        {
          name: 'Unicorn',
          rarity: 'Epic',
          dropRatePct: 5,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/medieval/unicorn.svg',
        },
        {
          name: 'King',
          rarity: 'Legendary',
          dropRatePct: 1.0,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/medieval/king.svg',
        },
      ],
    },
    {
      packId: 'wonderland',
      name: 'Wonderland Pack',
      costTokens: 20,
      poster: '/assets/blooket/packs/wonderlandpack.webp',
      blooks: [
        {
          name: 'Two of Spades',
          rarity: 'Uncommon',
          dropRatePct: 15.2,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/wonderland/twoofspades.svg',
        },
        {
          name: 'Eat Me',
          rarity: 'Uncommon',
          dropRatePct: 15,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/wonderland/eat.svg',
        },
        {
          name: 'Drink Me',
          rarity: 'Uncommon',
          dropRatePct: 15,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/wonderland/drink.svg',
        },
        {
          name: 'Alice',
          rarity: 'Uncommon',
          dropRatePct: 15,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/wonderland/alice.svg',
        },
        {
          name: 'Queen of Hearts',
          rarity: 'Uncommon',
          dropRatePct: 15,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/wonderland/queenofhearts.svg',
        },
        {
          name: 'Dormouse',
          rarity: 'Rare',
          dropRatePct: 6.5,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/wonderland/dormouse.svg',
        },
        {
          name: 'White Rabbit',
          rarity: 'Rare',
          dropRatePct: 6.5,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/wonderland/whiterabbit.svg',
        },
        {
          name: 'Cheshire Cat',
          rarity: 'Rare',
          dropRatePct: 6.5,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/wonderland/cheshirecat.svg',
        },
        {
          name: 'Caterpillar',
          rarity: 'Epic',
          dropRatePct: 2.5,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/wonderland/caterpillar.svg',
        },
        {
          name: 'Mad Hatter',
          rarity: 'Epic',
          dropRatePct: 2.5,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/wonderland/madhatter.svg',
        },
        {
          name: 'King of Hearts',
          rarity: 'Legendary',
          dropRatePct: 0.3,
          salePrice: 200,
          blookScore: 35,
          poster: '/assets/blooket/blooks/wonderland/kingofhearts.svg',
        },
      ],
    },
    {
      packId: 'breakfast',
      name: 'Breakfast Pack',
      costTokens: 20,
      poster: '/assets/blooket/packs/breakfastpack.webp',
      blooks: [
        {
          name: 'Toast',
          rarity: 'Uncommon',
          dropRatePct: 12.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/breakfast/toast.svg',
        },
        {
          name: 'Cereal',
          rarity: 'Uncommon',
          dropRatePct: 12.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/breakfast/cereal.svg',
        },
        {
          name: 'Yogurt',
          rarity: 'Uncommon',
          dropRatePct: 12.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/breakfast/yogurt.svg',
        },
        {
          name: 'Breakfast Combo',
          rarity: 'Uncommon',
          dropRatePct: 12.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/breakfast/breakfastcombo.svg',
        },
        {
          name: 'Orange Juice',
          rarity: 'Uncommon',
          dropRatePct: 12.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/breakfast/orangejuice.svg',
        },
        {
          name: 'Milk',
          rarity: 'Uncommon',
          dropRatePct: 12.5,
          salePrice: 5,
          blookScore: 5,
          poster: '/assets/blooket/blooks/breakfast/milk.svg',
        },
        {
          name: 'Waffle',
          rarity: 'Rare',
          dropRatePct: 9,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/breakfast/waffle.svg',
        },
        {
          name: 'Pancakes',
          rarity: 'Rare',
          dropRatePct: 9,
          salePrice: 20,
          blookScore: 10,
          poster: '/assets/blooket/blooks/breakfast/pancakes.svg',
        },
        {
          name: 'French Toast',
          rarity: 'Epic',
          dropRatePct: 5,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/breakfast/frenchtoast.svg',
        },
        {
          name: 'Pizza',
          rarity: 'Epic',
          dropRatePct: 2,
          salePrice: 75,
          blookScore: 20,
          poster: '/assets/blooket/blooks/breakfast/pizza.svg',
        },
      ],
    },
  ],
};
