export const countryData = {
  Taiwan: {
    code: 'TW',
    name: 'Taiwan',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.8, credits: 18 },
      semester2: { gpa: 4.0, credits: 16 },
    },
  },

  Malaysia: {
    code: 'MY',
    name: 'Malaysia',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.65, credits: 18 },
      semester2: { gpa: 3.9, credits: 20 },
    },
  },

  Philippines: {
    code: 'PH',
    name: 'Philippines',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Units',
      calculateCGPA: 'Calculate GWA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Units',
      resultCGPA: 'Your GWA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Units',
    },
    example: {
      semester1: { gpa: 2.5, credits: 18 },
      semester2: { gpa: 1.75, credits: 15 },
    },
  },

  'Hong Kong': {
    code: 'HK',
    name: 'Hong Kong',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.7, credits: 15 },
      semester2: { gpa: 3.9, credits: 18 },
    },
  },

  Singapore: {
    code: 'SG',
    name: 'Singapore',
    terms: {
      semesterGPA: 'Semester GPA (out of 5.0)',
      semesterCredits: 'Modular Credits (MCs)',
      calculateCGPA: 'Calculate CAP',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} MCs',
      resultCGPA: 'Your CAP Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Modular Credits',
    },
    example: {
      semester1: { gpa: 4.2, credits: 20 },
      semester2: { gpa: 4.5, credits: 20 },
    },
  },

  Egypt: {
    code: 'EG',
    name: 'Egypt',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: { gpa: 3.5, credits: 18 },
      semester2: { gpa: 3.8, credits: 20 },
    },
  },

  Pakistan: {
    code: 'PK',
    name: 'Pakistan',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.5, credits: 16 },
      semester2: { gpa: 3.8, credits: 18 },
    },
  },
  'United Kingdom': {
    code: 'GB',
    name: 'United Kingdom',
    terms: {
      semesterGPA: 'Semester Percentage',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate Degree Classification',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} Percentage',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your Degree Classification',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 68, credits: 60 },
      semester2: { gpa: 72, credits: 60 },
    },
  },
  India: {
    code: 'IN',
    name: 'India',
    terms: {
      semesterGPA: 'SGPA (out of 10.0)',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} SGPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 8.5, credits: 24 },
      semester2: { gpa: 9.1, credits: 22 },
    },
  },
  Germany: {
    code: 'DE',
    name: 'Germany',
    terms: {
      semesterGPA: 'Semester Durchschnittsnote',
      semesterCredits: 'Credit Points (CP)',
      calculateCGPA: 'Gesamtdurchschnittsnote berechnen',
      addSemester: 'Semester hinzufügen',
      deleteSemester: 'Semester löschen',
      placeholderGPA: 'Semester {{n}} Note',
      placeholderCredits: 'Semester {{n}} Credit Points (CP)',
      resultCGPA: 'Ihre Gesamtnote',
      resultTotalSemesters: 'Anzahl Semester',
      resultTotalCredits: 'Gesamt Credit Points',
    },
    example: {
      semester1: { gpa: 1.7, credits: 30 },
      semester2: { gpa: 1.3, credits: 30 },
    },
  },
  France: {
    code: 'FR',
    name: 'France',
    terms: {
      semesterGPA: 'Moyenne (out of 20)',
      semesterCredits: 'Crédits ECTS',
      calculateCGPA: 'Calculer la moyenne générale',
      addSemester: 'Ajouter un semestre',
      deleteSemester: 'Supprimer le semestre',
      placeholderGPA: 'Moyenne {{n}}',
      placeholderCredits: 'Crédits ECTS {{n}}',
      resultCGPA: 'Votre Moyenne Générale',
      resultTotalSemesters: 'Total de semestres',
      resultTotalCredits: 'Total de crédits',
    },
    example: {
      semester1: { gpa: 14.5, credits: 30 },
      semester2: { gpa: 15.2, credits: 30 },
    },
  },
  'United Arab Emirates': {
    code: 'AE',
    name: 'United Arab Emirates',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: { gpa: 3.5, credits: 15 },
      semester2: { gpa: 3.8, credits: 18 },
    },
  },
  Bangladesh: {
    code: 'BD',
    name: 'Bangladesh',
    terms: {
      semesterGPA: 'Semester GPA (out of 4.0)',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.5, credits: 15 },
      semester2: { gpa: 3.8, credits: 18 },
    },
  },
  Netherlands: {
    code: 'NL',
    name: 'Netherlands',
    terms: {
      semesterGPA: 'Gemiddelde (out of 10)',
      semesterCredits: 'Studiepunten (EC)',
      calculateCGPA: 'Gemiddelde cijfer berekenen',
      addSemester: 'Semester toevoegen',
      deleteSemester: 'Semester verwijderen',
      placeholderGPA: 'Gemiddelde {{n}}',
      placeholderCredits: 'Studiepunten (EC) {{n}}',
      resultCGPA: 'Uw gemiddelde cijfer',
      resultTotalSemesters: 'Totaal aantal semesters',
      resultTotalCredits: 'Totaal aantal studiepunten',
    },
    example: {
      semester1: { gpa: 7.5, credits: 30 },
      semester2: { gpa: 8.0, credits: 30 },
    },
  },
  'Saudi Arabia': {
    code: 'SA',
    name: 'Saudi Arabia',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: { gpa: 3.75, credits: 16 },
      semester2: { gpa: 4.0, credits: 18 },
    },
  },
  Turkey: {
    code: 'TR',
    name: 'Turkey',
    terms: {
      semesterGPA: 'Dönem Not Ortalaması (out of 4.0)',
      semesterCredits: 'AKTS (ECTS) / Kredi',
      calculateCGPA: 'GNO hesapla',
      addSemester: 'Dönem Ekle',
      deleteSemester: 'Dönem Sil',
      placeholderGPA: 'Dönem {{n}} Not Ortalaması',
      placeholderCredits: 'Dönem {{n}} Kredisi',
      resultCGPA: 'GNO Sonucunuz',
      resultTotalSemesters: 'Toplam Dönem Sayısı',
      resultTotalCredits: 'Toplam Kredi',
    },
    example: {
      semester1: { gpa: 3.2, credits: 30 },
      semester2: { gpa: 3.5, credits: 30 },
    },
  },
  Nepal: {
    code: 'NP',
    name: 'Nepal',
    terms: {
      semesterGPA: 'Semester GPA (out of 4.0)',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.2, credits: 16 },
      semester2: { gpa: 3.5, credits: 18 },
    },
  },
  Nigeria: {
    code: 'NG',
    name: 'Nigeria',
    terms: {
      semesterGPA: 'Semester GPA (out of 5.0)',
      semesterCredits: 'Credit Units',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Units',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Units',
    },
    example: {
      semester1: { gpa: 4.2, credits: 18 },
      semester2: { gpa: 4.5, credits: 20 },
    },
  },
  'Sri Lanka': {
    code: 'LK',
    name: 'Sri Lanka',
    terms: {
      semesterGPA: 'Semester GPA (SGPA)',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.2, credits: 15 },
      semester2: { gpa: 3.5, credits: 18 },
    },
  },
  Indonesia: {
    code: 'ID',
    name: 'Indonesia',
    terms: {
      semesterGPA: 'IP Semester',
      semesterCredits: 'SKS',
      calculateCGPA: 'Hitung IPK',
      addSemester: 'Tambah Semester',
      deleteSemester: 'Hapus Semester',
      placeholderGPA: 'IP Semester {{n}}',
      placeholderCredits: 'SKS Semester {{n}}',
      resultCGPA: 'Your IPK Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.2, credits: 20 },
      semester2: { gpa: 3.5, credits: 22 },
    },
  },
  Cyprus: {
    code: 'CY',
    name: 'Cyprus',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits / ECTS',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits / ECTS',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.5, credits: 30 },
      semester2: { gpa: 3.8, credits: 30 },
    },
  },
  Qatar: {
    code: 'QA',
    name: 'Qatar',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: { gpa: 3.6, credits: 15 },
      semester2: { gpa: 3.9, credits: 16 },
    },
  },
  'South Korea': {
    code: 'KR',
    name: 'South Korea',
    terms: {
      semesterGPA: 'Semester GPA (out of 4.5)',
      semesterCredits: 'Credits (학점)',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 4.1, credits: 18 },
      semester2: { gpa: 4.3, credits: 20 },
    },
  },
  Tunisia: {
    code: 'TN',
    name: 'Tunisia',
    terms: {
      semesterGPA: 'Moyenne (out of 20)',
      semesterCredits: 'Crédits ECTS',
      calculateCGPA: 'Calculer la moyenne générale',
      addSemester: 'Ajouter un semestre',
      deleteSemester: 'Supprimer le semestre',
      placeholderGPA: 'Moyenne {{n}}',
      placeholderCredits: 'Crédits ECTS {{n}}',
      resultCGPA: 'Votre Moyenne Générale',
      resultTotalSemesters: 'Total de semestres',
      resultTotalCredits: 'Total de crédits',
    },
    example: {
      semester1: { gpa: 12.5, credits: 30 },
      semester2: { gpa: 14.8, credits: 30 },
    },
  },
  Brunei: {
    code: 'BN',
    name: 'Brunei',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits / Modular Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.5, credits: 18 },
      semester2: { gpa: 3.8, credits: 20 },
    },
  },
  Australia: {
    code: 'AU',
    name: 'Australia',
    terms: {
      semesterGPA: 'Semester GPA (out of 7.0)',
      semesterCredits: 'Credits / Credit Points',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 5.5, credits: 24 },
      semester2: { gpa: 6.2, credits: 24 },
    },
  },
  Hungary: {
    code: 'HU',
    name: 'Hungary',
    terms: {
      semesterGPA: 'Szemeszter Átlag (out of 5.0)',
      semesterCredits: 'Kredit (ECTS)',
      calculateCGPA: 'Szemeszter Átlag számítása',
      addSemester: 'Szemeszter hozzáadása',
      deleteSemester: 'Szemeszter törlése',
      placeholderGPA: 'Szemeszter {{n}} Átlag',
      placeholderCredits: 'Szemeszter {{n}} Kredit (ECTS)',
      resultCGPA: 'Szemeszter Átlag',
      resultTotalSemesters: 'Összes félév',
      resultTotalCredits: 'Összes kredit',
    },
    example: {
      semester1: { gpa: 4.5, credits: 30 },
      semester2: { gpa: 4.8, credits: 30 },
    },
  },
  Azerbaijan: {
    code: 'AZ',
    name: 'Azerbaijan',
    terms: {
      semesterGPA: 'GPA (out of 4.0)',
      semesterCredits: 'Credits / Kredit',
      calculateCGPA: 'GPA hesablayın',
      addSemester: 'Semestr əlavə et',
      deleteSemester: 'Semestri sil',
      placeholderGPA: 'Semestr {{n}} GPA',
      placeholderCredits: 'Semestr {{n}} Kredit',
      resultCGPA: 'GPA nəticəniz',
      resultTotalSemesters: 'Ümumi semestr',
      resultTotalCredits: 'Ümumi kredit',
    },
    example: {
      semester1: { gpa: 3.5, credits: 30 },
      semester2: { gpa: 3.8, credits: 30 },
    },
  },
  Ireland: {
    code: 'IE',
    name: 'Ireland',
    terms: {
      semesterGPA: 'Semester Percentage',
      semesterCredits: 'Credits / ECTS',
      calculateCGPA: 'Calculate Overall Percentage',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} Percentage',
      placeholderCredits: 'Semester {{n}} Credits / ECTS',
      resultCGPA: 'Your Overall Percentage',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 78, credits: 30 },
      semester2: { gpa: 72, credits: 30 },
    },
  },

  Japan: {
    code: 'JP',
    name: 'Japan',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits (単位)',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.5, credits: 18 },
      semester2: { gpa: 3.8, credits: 20 },
    },
  },
  Italy: {
    code: 'IT',
    name: 'Italy',
    terms: {
      semesterGPA: 'Moyenne par semestre (out of 30)',
      semesterCredits: 'Crediti Formativi Universitari (CFU)',
      calculateCGPA: 'Calcolare la media generale',
      addSemester: 'Aggiungi semestre',
      deleteSemester: 'Elimina semestre',
      placeholderGPA: 'Voto medio {{n}}',
      placeholderCredits: 'Crediti {{n}}',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 25, credits: 30 },
      semester2: { gpa: 28, credits: 30 },
    },
  },
  Kuwait: {
    code: 'KW',
    name: 'Kuwait',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: { gpa: 3.6, credits: 15 },
      semester2: { gpa: 3.9, credits: 16 },
    },
  },
  Poland: {
    code: 'PL',
    name: 'Poland',
    terms: {
      semesterGPA: 'Średnia ocen (out of 5.0)',
      semesterCredits: 'Punkty ECTS',
      calculateCGPA: 'Średnia ważona ocen',
      addSemester: 'Dodaj semestr',
      deleteSemester: 'Usuń semestr',
      placeholderGPA: 'Średnia ocen {{n}}',
      placeholderCredits: 'Punkty ECTS {{n}}',
      resultCGPA: 'Średnia ważona ocen',
      resultTotalSemesters: 'Całkowita liczba semestrów',
      resultTotalCredits: 'Całkowita liczba punktów ECTS',
    },
    example: {
      semester1: { gpa: 4.2, credits: 30 },
      semester2: { gpa: 4.5, credits: 30 },
    },
  },
  Bahrain: {
    code: 'BH',
    name: 'Bahrain',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: { gpa: 3.6, credits: 15 },
      semester2: { gpa: 3.9, credits: 16 },
    },
  },
  Thailand: {
    code: 'TH',
    name: 'Thailand',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits / Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.5, credits: 18 },
      semester2: { gpa: 3.8, credits: 20 },
    },
  },
  Morocco: {
    code: 'MA',
    name: 'Morocco',
    terms: {
      semesterGPA: 'Moyenne par semestre (out of 20)',
      semesterCredits: 'Crédits',
      calculateCGPA: 'Calculer la moyenne générale',
      addSemester: 'Ajouter un semestre',
      deleteSemester: 'Supprimer le semestre',
      placeholderGPA: 'Moyenne {{n}}',
      placeholderCredits: 'Crédits {{n}}',
      resultCGPA: 'Votre Moyenne Générale',
      resultTotalSemesters: 'Total de semestres',
      resultTotalCredits: 'Total de crédits',
    },
    example: {
      semester1: { gpa: 12.5, credits: 30 },
      semester2: { gpa: 14.8, credits: 30 },
    },
  },
  Switzerland: {
    code: 'CH',
    name: 'Switzerland',
    terms: {
      semesterGPA: 'Semesterdurchschnitt (out of 6.0)',
      semesterCredits: 'Credits / ECTS',
      calculateCGPA: 'Gesamtdurchschnitt berechnen',
      addSemester: 'Semester hinzufügen',
      deleteSemester: 'Semester löschen',
      placeholderGPA: 'Semester {{n}} Durchschnitt',
      placeholderCredits: 'Semester {{n}} Credits / ECTS',
      resultCGPA: 'Gesamtdurchschnitt',
      resultTotalSemesters: 'Gesamtanzahl Semester',
      resultTotalCredits: 'Gesamte Credits',
    },
    example: {
      semester1: { gpa: 5.2, credits: 30 },
      semester2: { gpa: 5.5, credits: 30 },
    },
  },
  China: {
    code: 'CN',
    name: 'China',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits (学分)',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.5, credits: 20 },
      semester2: { gpa: 3.8, credits: 22 },
    },
  },
  Romania: {
    code: 'RO',
    name: 'Romania',
    terms: {
      semesterGPA: 'Media semestrială (out of 10)',
      semesterCredits: 'Credite ECTS',
      calculateCGPA: 'Calculare media generală',
      addSemester: 'Adaugă semestru',
      deleteSemester: 'Șterge semestru',
      placeholderGPA: 'Media semestrului {{n}}',
      placeholderCredits: 'Credite {{n}}',
      resultCGPA: 'Media generală',
      resultTotalSemesters: 'Total semestre',
      resultTotalCredits: 'Total credite',
    },
    example: {
      semester1: { gpa: 8.5, credits: 30 },
      semester2: { gpa: 9.1, credits: 30 },
    },
  },
  Jordan: {
    code: 'JO',
    name: 'Jordan',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: { gpa: 3.5, credits: 15 },
      semester2: { gpa: 3.8, credits: 16 },
    },
  },
  'New Zealand': {
    code: 'NZ',
    name: 'New Zealand',
    terms: {
      semesterGPA: 'Semester GPA (out of 9.0)',
      semesterCredits: 'Points',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Points',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Points',
    },
    example: {
      semester1: { gpa: 6.5, credits: 60 },
      semester2: { gpa: 7.2, credits: 60 },
    },
  },
  Brazil: {
    code: 'BR',
    name: 'Brazil',
    terms: {
      semesterGPA: 'Média Semestral (out of 10)',
      semesterCredits: 'Créditos',
      calculateCGPA: 'Calcular Coeficiente de Rendimento',
      addSemester: 'Adicionar Semestre',
      deleteSemester: 'Excluir Semestre',
      placeholderGPA: 'Média Semestral {{n}}',
      placeholderCredits: 'Créditos {{n}}',
      resultCGPA: 'Coeficiente de Rendimento',
      resultTotalSemesters: 'Total de Semestres',
      resultTotalCredits: 'Total de Créditos',
    },
    example: {
      semester1: { gpa: 8.5, credits: 24 },
      semester2: { gpa: 9.1, credits: 22 },
    },
  },
  Spain: {
    code: 'ES',
    name: 'Spain',
    terms: {
      semesterGPA: 'Nota media (out of 10)',
      semesterCredits: 'Créditos ECTS',
      calculateCGPA: 'Calcular la nota media general',
      addSemester: 'Añadir semestre',
      deleteSemester: 'Eliminar semestre',
      placeholderGPA: 'Nota media {{n}}',
      placeholderCredits: 'Créditos {{n}}',
      resultCGPA: 'Nota media general',
      resultTotalSemesters: 'Total de semestres',
      resultTotalCredits: 'Total de Créditos',
    },
    example: {
      semester1: { gpa: 8.5, credits: 30 },
      semester2: { gpa: 9.1, credits: 30 },
    },
  },
  'United States': {
    code: 'US',
    name: 'United States',
    terms: {
      semesterGPA: 'Term GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.5, credits: 15 },
      semester2: { gpa: 3.8, credits: 16 },
    },
  },
  Canada: {
    code: 'CA',
    name: 'Canada',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits / Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: { gpa: 3.5, credits: 15 },
      semester2: { gpa: 3.8, credits: 18 },
    },
  },
  Ghana: {
    code: 'GH',
    name: 'Ghana',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: { gpa: 3.5, credits: 15 },
      semester2: { gpa: 3.8, credits: 16 },
    },
  },
  Ethiopia: {
    code: 'ET',
    name: 'Ethiopia',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: { gpa: 3.5, credits: 16 },
      semester2: { gpa: 3.8, credits: 18 },
    },
  },
  Oman: {
    code: 'OM',
    name: 'Oman',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: { gpa: 3.5, credits: 15 },
      semester2: { gpa: 3.8, credits: 16 },
    },
  },
  Uganda: {
    code: 'UG',
    name: 'Uganda',
    terms: {
      semesterGPA: 'Semester GPA (out of 5.0)',
      semesterCredits: 'Credit Units',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Units',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Units',
    },
    example: {
      semester1: { gpa: 4.2, credits: 18 },
      semester2: { gpa: 4.5, credits: 20 },
    },
  },
};
