export const countryData = {
  Taiwan: {
    code: 'TW',
    name: 'Taiwan',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.8,
        credits: 18,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 4.0,
        credits: 16,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },

  Malaysia: {
    code: 'MY',
    name: 'Malaysia',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.65,
        credits: 18,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.9,
        credits: 20,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },

  Philippines: {
    code: 'PH',
    name: 'Philippines',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Units',
      calculateCGPA: 'Calculate GWA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Units',
      resultCGPA: 'Your GWA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Units',
    },
    example: {
      semester1: {
        gpa: 2.5,
        credits: 18,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Units',
      },
      semester2: {
        gpa: 1.75,
        credits: 15,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Units',
      },
    },
  },

  'Hong Kong': {
    code: 'HK',
    name: 'Hong Kong',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.7,
        credits: 15,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 3.9,
        credits: 18,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },

  Singapore: {
    code: 'SG',
    name: 'Singapore',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Modular Credits (MCs)',
      calculateCGPA: 'Calculate CAP/CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} MCs',
      resultCGPA: 'Your CAP/CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Modular Credits',
    },
    example: {
      semester1: {
        gpa: 3.9,
        credits: 20,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 3.7,
        credits: 20,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },

  Egypt: {
    code: 'EG',
    name: 'Egypt',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 18,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.8,
        credits: 20,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },

  Pakistan: {
    code: 'PK1',
    name: 'Pakistan',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 16,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.8,
        credits: 18,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },
  'United Kingdom': {
    code: 'GB',
    name: 'United Kingdom',
    terms: {
      semesterGPA: 'Semester Percentage',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate Degree Classification',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} Percentage',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your Degree Classification',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 68,
        credits: 60,
        GPATerm: 'Semester 1 Percentage',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 72,
        credits: 60,
        GPATerm: 'Semester 2 Percentage',
        creditsTerm: 'Credits',
      },
    },
  },
  India: {
    code: 'IN',
    name: 'India',
    terms: {
      semesterGPA: 'SGPA (out of 10.0)',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 8.5,
        credits: 24,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 9.1,
        credits: 22,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
    },
  },
  Germany: {
    code: 'DE',
    name: 'Germany',
    terms: {
      semesterGPA: 'Semester Durchschnittsnote',
      semesterCredits: 'Credit Points (CP)',
      calculateCGPA: 'Gesamtdurchschnittsnote berechnen',
      addSemester: 'Semester hinzufügen',
      deleteSemester: 'Semester löschen',
      placeholderGPA: 'Semester {{n}} Note',
      placeholderCredits: 'Semester {{n}} Credit Points (CP)',
      resultCGPA: 'Ihre Gesamtnote',
      resultTotalSemesters: 'Anzahl Semester',
      resultTotalCredits: 'Gesamt Credit Points',
    },
    example: {
      semester1: {
        gpa: 1.7,
        credits: 30,
        GPATerm: 'Semester 1 Note',
        creditsTerm: 'Credit Points',
      },
      semester2: {
        gpa: 1.3,
        credits: 30,
        GPATerm: 'Semester 2 Note',
        creditsTerm: 'Credit Points',
      },
    },
  },
  France: {
    code: 'FR',
    name: 'France',
    terms: {
      semesterGPA: 'Moyenne',
      semesterCredits: 'Crédits ECTS',
      calculateCGPA: 'Calculer la moyenne générale',
      addSemester: 'Ajouter un semestre',
      deleteSemester: 'Supprimer le semestre',
      placeholderGPA: 'Moyenne {{n}}',
      placeholderCredits: 'Crédits ECTS {{n}}',
      resultCGPA: 'Votre Moyenne Générale',
      resultTotalSemesters: 'Total de semestres',
      resultTotalCredits: 'Total de crédits',
    },
    example: {
      semester1: {
        gpa: 14.5,
        credits: '30/60',
        GPATerm: 'Moyenne 1',
        creditsTerm: 'Crédits ECTS',
      },
      semester2: {
        gpa: 15.2,
        credits: '30/60',
        GPATerm: 'Moyenne 2',
        creditsTerm: 'Crédits ECTS',
      },
    },
  },
  'United Arab Emirates': {
    code: 'AE-AR',
    name: 'United Arab Emirates',
    terms: {
      semesterGPA: 'المعدل الفصلي',
      semesterCredits: 'الساعات المعتمدة',
      calculateCGPA: 'حساب المعدل التراكمي',
      addSemester: 'إضافة فصل دراسي',
      deleteSemester: 'حذف فصل دراسي',
      placeholderGPA: 'المعدل الفصلي {{n}}',
      placeholderCredits: 'ساعات معتمدة {{n}}',
      resultCGPA: 'معدلك التراكمي',
      resultTotalSemesters: 'إجمالي الفصول الدراسية',
      resultTotalCredits: 'إجمالي الساعات المعتمدة',
    },
    example: {
      semester1: {
        gpa: 3.6,
        credits: 16,
        GPATerm: 'المعدل الفصلي 1',
        creditsTerm: 'الساعات المعتمدة',
      },
      semester2: {
        gpa: 3.9,
        credits: 14,
        GPATerm: 'المعدل الفصلي 2',
        creditsTerm: 'الساعات المعتمدة',
      },
    },
  },
  'United Arab Emirates (English)': {
    code: 'AE',
    name: 'United Arab Emirates (English)',
    terms: {
      semesterGPA: 'Semester GPA (out of 4.0)',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Credit Hours {{n}}',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: {
        gpa: 3.6,
        credits: 16,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.9,
        credits: 14,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },
  Bangladesh: {
    code: 'BD',
    name: 'Bangladesh',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 15,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 3.8,
        credits: 18,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },
  Netherlands: {
    code: 'NL',
    name: 'Netherlands',
    terms: {
      semesterGPA: 'Gemiddelde',
      semesterCredits: 'Studiepunten (EC)',
      calculateCGPA: 'Gemiddelde cijfer berekenen',
      addSemester: 'Semester toevoegen',
      deleteSemester: 'Semester verwijderen',
      placeholderGPA: 'Gemiddelde {{n}}',
      placeholderCredits: 'Studiepunten (EC) {{n}}',
      resultCGPA: 'Uw gemiddelde cijfer',
      resultTotalSemesters: 'Totaal aantal semesters',
      resultTotalCredits: 'Totaal aantal studiepunten',
    },
    example: {
      semester1: {
        gpa: 7.5,
        credits: 30,
        GPATerm: 'Gemiddelde 1',
        creditsTerm: 'Studiepunten (EC)',
      },
      semester2: {
        gpa: 8.0,
        credits: 30,
        GPATerm: 'Gemiddelde 2',
        creditsTerm: 'Studiepunten (EC)',
      },
    },
  },
  'Saudi Arabia': {
    code: 'SA',
    name: 'Saudi Arabia',
    terms: {
      semesterGPA: 'المعدل الفصلي',
      semesterCredits: 'الساعات المعتمدة',
      calculateCGPA: 'حساب المعدل التراكمي',
      addSemester: 'إضافة فصل دراسي',
      deleteSemester: 'حذف فصل دراسي',
      placeholderGPA: 'المعدل الفصلي {{n}}',
      placeholderCredits: 'ساعات معتمدة {{n}}',
      resultCGPA: 'معدلك التراكمي',
      resultTotalSemesters: 'إجمالي الفصول الدراسية',
      resultTotalCredits: 'إجمالي الساعات المعتمدة',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 15,
        GPATerm: 'المعدل الفصلي 1',
        creditsTerm: 'الساعات المعتمدة',
      },
      semester2: {
        gpa: 3.8,
        credits: 18,
        GPATerm: 'المعدل الفصلي 2',
        creditsTerm: 'الساعات المعتمدة',
      },
    },
  },
  Turkey: {
    code: 'TR',
    name: 'Turkey',
    terms: {
      semesterGPA: 'Dönem GNO (out of 4.0)',
      semesterCredits: 'AKTS / Kredi',
      calculateCGPA: 'GNO hesapla',
      addSemester: 'Dönem Ekle',
      deleteSemester: 'Dönem Sil',
      placeholderGPA: 'Dönem {{n}} GNO',
      placeholderCredits: 'Dönem {{n}} Kredi',
      resultCGPA: 'GNO Sonucunuz',
      resultTotalSemesters: 'Toplam Dönem Sayısı',
      resultTotalCredits: 'Toplam Kredi',
    },
    example: {
      semester1: {
        gpa: 3.2,
        credits: 30,
        GPATerm: 'Dönem 1 GNO',
        creditsTerm: 'Kredi',
      },
      semester2: {
        gpa: 3.5,
        credits: 30,
        GPATerm: 'Dönem 2 GNO',
        creditsTerm: 'Kredi',
      },
    },
  },
  Nepal: {
    code: 'NP',
    name: 'Nepal',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.2,
        credits: 16,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 3.5,
        credits: 18,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },
  Nigeria: {
    code: 'NG',
    name: 'Nigeria',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Units',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Units',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Units',
    },
    example: {
      semester1: {
        gpa: 4.2,
        credits: 18,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Units',
      },
      semester2: {
        gpa: 4.5,
        credits: 20,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Units',
      },
    },
  },
  'Sri Lanka': {
    code: 'LK',
    name: 'Sri Lanka',
    terms: {
      semesterGPA: 'Semester GPA (SGPA)',
      semesterCredits: 'Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.2,
        credits: 15,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 3.5,
        credits: 18,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },
  Indonesia: {
    code: 'ID',
    name: 'Indonesia',
    terms: {
      semesterGPA: 'IP Semester',
      semesterCredits: 'SKS',
      calculateCGPA: 'Hitung IPK',
      addSemester: 'Tambah Semester',
      deleteSemester: 'Hapus Semester',
      placeholderGPA: 'IP Semester {{n}}',
      placeholderCredits: 'SKS Semester {{n}}',
      resultCGPA: 'Your IPK Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.2,
        credits: 20,
        GPATerm: 'IP Semester 1',
        creditsTerm: 'SKS',
      },
      semester2: {
        gpa: 3.5,
        credits: 22,
        GPATerm: 'IP Semester 2',
        creditsTerm: 'SKS',
      },
    },
  },
  Cyprus: {
    code: 'CY',
    name: 'Cyprus',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits / ECTS',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits / ECTS',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 30,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 3.8,
        credits: 30,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },
  Qatar: {
    code: 'QA',
    name: 'Qatar',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: {
        gpa: 3.6,
        credits: 15,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.9,
        credits: 16,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },
  'South Korea (English)': {
    code: 'KR-EN',
    name: 'South Korea (English)',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits (학점)',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 4.1,
        credits: 18,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits (학점)',
      },
      semester2: {
        gpa: 4.3,
        credits: 20,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits (학점)',
      },
    },
  },
  'South Korea (한국인)': {
    code: 'KR',
    name: 'South Korea (한국인)',
    terms: {
      semesterGPA: '학기 평점 평균',
      semesterCredits: '학점',
      calculateCGPA: '누적 평점 평균 계산',
      addSemester: '학기 추가',
      deleteSemester: '학기 삭제',
      placeholderGPA: '평점 평균 학기 {{n}}',
      placeholderCredits: '학점 {{n}}',
      resultCGPA: '당신의 누적 평점 평균',
      resultTotalSemesters: '총 학기 수',
      resultTotalCredits: '총 학점',
    },
    example: {
      semester1: {
        gpa: 4.1,
        credits: 18,
        GPATerm: '평점 평균 학기 1',
        creditsTerm: '학점',
      },
      semester2: {
        gpa: 4.4,
        credits: 17,
        GPATerm: '평점 평균 학기 2',
        creditsTerm: '학점',
      },
    },
  },
  Tunisia: {
    code: 'TN',
    name: 'Tunisia',
    terms: {
      semesterGPA: 'Moyenne',
      semesterCredits: 'Crédits ECTS',
      calculateCGPA: 'Calculer la moyenne générale',
      addSemester: 'Ajouter un semestre',
      deleteSemester: 'Supprimer le semestre',
      placeholderGPA: 'Moyenne {{n}}',
      placeholderCredits: 'Crédits ECTS {{n}}',
      resultCGPA: 'Votre Moyenne Générale',
      resultTotalSemesters: 'Total de semestres',
      resultTotalCredits: 'Total de crédits',
    },
    example: {
      semester1: {
        gpa: 12.5,
        credits: 30,
        GPATerm: 'Moyenne 1',
        creditsTerm: 'Crédits ECTS',
      },
      semester2: {
        gpa: 14.8,
        credits: 30,
        GPATerm: 'Moyenne 2',
        creditsTerm: 'Crédits ECTS',
      },
    },
  },
  Brunei: {
    code: 'BN',
    name: 'Brunei',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits / Modular Credits',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 18,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 3.8,
        credits: 20,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },
  Australia: {
    code: 'AU',
    name: 'Australia',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits / Credit Points',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 5.5,
        credits: 24,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 6.2,
        credits: 24,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },
  Hungary: {
    code: 'HU',
    name: 'Hungary',
    terms: {
      semesterGPA: 'Szemeszter Átlag',
      semesterCredits: 'Kredit (ECTS)',
      calculateCGPA: 'Szemeszter Átlag számítása',
      addSemester: 'Szemeszter hozzáadása',
      deleteSemester: 'Szemeszter törlése',
      placeholderGPA: 'Szemeszter {{n}} Átlag',
      placeholderCredits: 'Szemeszter {{n}} Kredit (ECTS)',
      resultCGPA: 'Szemeszter Átlag',
      resultTotalSemesters: 'Összes félév',
      resultTotalCredits: 'Összes kredit',
    },
    example: {
      semester1: {
        gpa: 4.5,
        credits: 30,
        GPATerm: 'Szemeszter 1 Átlag',
        creditsTerm: 'Kredit',
      },
      semester2: {
        gpa: 4.8,
        credits: 30,
        GPATerm: 'Szemeszter 2 Átlag',
        creditsTerm: 'Kredit',
      },
    },
  },
  Azerbaijan: {
    code: 'AZ',
    name: 'Azerbaijan',
    terms: {
      semesterGPA: 'GPA',
      semesterCredits: 'Credits / Kredit',
      calculateCGPA: 'GPA hesablayın',
      addSemester: 'Semestr əlavə et',
      deleteSemester: 'Semestri sil',
      placeholderGPA: 'Semestr {{n}} GPA',
      placeholderCredits: 'Semestr {{n}} Kredit',
      resultCGPA: 'GPA nəticəniz',
      resultTotalSemesters: 'Ümumi semestr',
      resultTotalCredits: 'Ümumi kredit',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 30,
        GPATerm: 'Semestr 1 GPA',
        creditsTerm: 'Kredit',
      },
      semester2: {
        gpa: 3.8,
        credits: 30,
        GPATerm: 'Semestr 2 GPA',
        creditsTerm: 'Kredit',
      },
    },
  },
  Ireland: {
    code: 'IE',
    name: 'Ireland',
    terms: {
      semesterGPA: 'Semester Percentage',
      semesterCredits: 'Credits / ECTS',
      calculateCGPA: 'Calculate Overall Percentage',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} Percentage',
      placeholderCredits: 'Semester {{n}} Credits / ECTS',
      resultCGPA: 'Your Overall Percentage',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 78,
        credits: 30,
        GPATerm: 'Semester 1 Percentage',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 72,
        credits: 30,
        GPATerm: 'Semester 2 Percentage',
        creditsTerm: 'Credits',
      },
    },
  },

  'Japan (English)': {
    code: 'JP-EN',
    name: 'Japan (English)',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits (単位)',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 18,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits (単位)',
      },
      semester2: {
        gpa: 3.8,
        credits: 20,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits (単位)',
      },
    },
  },
  'Japan (日本語)': {
    code: 'JP',
    name: 'Japan (日本語)',
    terms: {
      semesterGPA: '学期GPA',
      semesterCredits: '単位',
      calculateCGPA: '累積GPAを計算する',
      addSemester: '学期を追加',
      deleteSemester: '学期を削除',
      placeholderGPA: 'GPA 学期 {{n}}',
      placeholderCredits: '単位数 {{n}}',
      resultCGPA: 'あなたの累積GPA',
      resultTotalSemesters: '総学期数',
      resultTotalCredits: '総単位数',
    },
    example: {
      semester1: {
        gpa: 3.2,
        credits: 15,
        GPATerm: 'GPA 学期 1',
        creditsTerm: '単位数',
      },
      semester2: {
        gpa: 3.7,
        credits: 16,
        GPATerm: 'GPA 学期 2',
        creditsTerm: '単位数',
      },
    },
  },
  Italy: {
    code: 'IT',
    name: 'Italy',
    terms: {
      semesterGPA: 'Moyenne par semestre',
      semesterCredits: 'Crediti Formativi Universitari (CFU)',
      calculateCGPA: 'Calcolare la media generale',
      addSemester: 'Aggiungi semestre',
      deleteSemester: 'Elimina semestre',
      placeholderGPA: 'Voto medio {{n}}',
      placeholderCredits: 'Crediti {{n}}',
      resultCGPA: 'La tua media generale',
      resultTotalSemesters: 'Numero totale di semestri',
      resultTotalCredits: 'Crediti totali',
    },
    example: {
      semester1: {
        gpa: 25,
        credits: '30/60',
        GPATerm: 'Voto medio 1',
        creditsTerm: 'Crediti',
      },
      semester2: {
        gpa: 28,
        credits: '30/60',
        GPATerm: 'Voto medio 2',
        creditsTerm: 'Crediti',
      },
    },
  },
  Kuwait: {
    code: 'KW',
    name: 'Kuwait',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: {
        gpa: 3.6,
        credits: 15,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.9,
        credits: 16,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },
  Poland: {
    code: 'PL',
    name: 'Poland',
    terms: {
      semesterGPA: 'Średnia ocen',
      semesterCredits: 'Punkty ECTS',
      calculateCGPA: 'Średnia ważona ocen',
      addSemester: 'Dodaj semestr',
      deleteSemester: 'Usuń semestr',
      placeholderGPA: 'Średnia ocen {{n}}',
      placeholderCredits: 'Punkty ECTS {{n}}',
      resultCGPA: 'Średnia ważona ocen',
      resultTotalSemesters: 'Całkowita liczba semestrów',
      resultTotalCredits: 'Całkowita liczba punktów ECTS',
    },
    example: {
      semester1: {
        gpa: 4.2,
        credits: 30,
        GPATerm: 'Średnia ocen 1',
        creditsTerm: 'Punkty ECTS',
      },
      semester2: {
        gpa: 4.5,
        credits: 30,
        GPATerm: 'Średnia ocen 2',
        creditsTerm: 'Punkty ECTS',
      },
    },
  },
  Bahrain: {
    code: 'BH',
    name: 'Bahrain',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: {
        gpa: 3.6,
        credits: 15,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.9,
        credits: 16,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },
  Thailand: {
    code: 'TH',
    name: 'Thailand',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits / Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 18,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 3.8,
        credits: 20,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },
  Morocco: {
    code: 'MA',
    name: 'Morocco',
    terms: {
      semesterGPA: 'Moyenne par semestre',
      semesterCredits: 'Crédits',
      calculateCGPA: 'Calculer la moyenne générale',
      addSemester: 'Ajouter un semestre',
      deleteSemester: 'Supprimer le semestre',
      placeholderGPA: 'Moyenne {{n}}',
      placeholderCredits: 'Crédits {{n}}',
      resultCGPA: 'Votre Moyenne Générale',
      resultTotalSemesters: 'Total de semestres',
      resultTotalCredits: 'Total de crédits',
    },
    example: {
      semester1: {
        gpa: 12.5,
        credits: 30,
        GPATerm: 'Moyenne 1',
        creditsTerm: 'Crédits',
      },
      semester2: {
        gpa: 14.8,
        credits: 30,
        GPATerm: 'Moyenne 2',
        creditsTerm: 'Crédits',
      },
    },
  },
  Switzerland: {
    code: 'CH',
    name: 'Switzerland',
    terms: {
      semesterGPA: 'Semesterdurchschnitt',
      semesterCredits: 'Credits / ECTS',
      calculateCGPA: 'Gesamtdurchschnitt berechnen',
      addSemester: 'Semester hinzufügen',
      deleteSemester: 'Semester löschen',
      placeholderGPA: 'Semester {{n}} Durchschnitt',
      placeholderCredits: 'Semester {{n}} Credits / ECTS',
      resultCGPA: 'Gesamtdurchschnitt',
      resultTotalSemesters: 'Gesamtanzahl Semester',
      resultTotalCredits: 'Gesamte Credits',
    },
    example: {
      semester1: {
        gpa: 5.2,
        credits: 30,
        GPATerm: 'Semester 1 Durchschnitt',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 5.5,
        credits: 30,
        GPATerm: 'Semester 2 Durchschnitt',
        creditsTerm: 'Credits',
      },
    },
  },
  'China (English)': {
    code: 'CN-EN',
    name: 'China (English)',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits (学分)',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 20,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 3.8,
        credits: 22,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },
  'China (中国人)': {
    code: 'CN',
    name: 'China (中国人)',
    terms: {
      semesterGPA: '学期平均绩点 ',
      semesterCredits: '学分',
      calculateCGPA: '计算累计平均绩点',
      addSemester: '添加学期',
      deleteSemester: '删除学期',
      placeholderGPA: '平均绩点 {{n}}',
      placeholderCredits: '学分 {{n}}',
      resultCGPA: '您的累计平均绩点',
      resultTotalSemesters: '总学期数',
      resultTotalCredits: '总学分',
    },
    example: {
      semester1: {
        gpa: 3.6,
        credits: 17,
        GPATerm: '学期 1 平均绩点',
        creditsTerm: '学分',
      },
      semester2: {
        gpa: 3.9,
        credits: 16,
        GPATerm: '学期 2 平均绩点',
        creditsTerm: '学分',
      },
    },
  },
  Romania: {
    code: 'RO',
    name: 'Romania',
    terms: {
      semesterGPA: 'Media semestrială',
      semesterCredits: 'Credite ECTS',
      calculateCGPA: 'Calculare media generală',
      addSemester: 'Adaugă semestru',
      deleteSemester: 'Șterge semestru',
      placeholderGPA: 'Media semestrului {{n}}',
      placeholderCredits: 'Credite {{n}}',
      resultCGPA: 'Media generală',
      resultTotalSemesters: 'Total semestre',
      resultTotalCredits: 'Total credite',
    },
    example: {
      semester1: {
        gpa: 8.5,
        credits: 30,
        GPATerm: 'Media semestrului 1',
        creditsTerm: 'Credite',
      },
      semester2: {
        gpa: 9.1,
        credits: 30,
        GPATerm: 'Media semestrului 2',
        creditsTerm: 'Credite',
      },
    },
  },
  Jordan: {
    code: 'JO',
    name: 'Jordan',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 15,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.8,
        credits: 16,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },
  'New Zealand': {
    code: 'NZ',
    name: 'New Zealand',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Points',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Points',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Points',
    },
    example: {
      semester1: {
        gpa: 6.5,
        credits: 60,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Points',
      },
      semester2: {
        gpa: 7.2,
        credits: 90,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Points',
      },
    },
  },
  Brazil: {
    code: 'BR',
    name: 'Brazil',
    terms: {
      semesterGPA: 'Média Semestral',
      semesterCredits: 'Créditos',
      calculateCGPA: 'Calcular Coeficiente de Rendimento',
      addSemester: 'Adicionar Semestre',
      deleteSemester: 'Excluir Semestre',
      placeholderGPA: 'Média Semestral {{n}}',
      placeholderCredits: 'Créditos {{n}}',
      resultCGPA: 'Coeficiente de Rendimento',
      resultTotalSemesters: 'Total de Semestres',
      resultTotalCredits: 'Total de Créditos',
    },
    example: {
      semester1: {
        gpa: 8.5,
        credits: 24,
        GPATerm: 'Média Semestral 1',
        creditsTerm: 'Créditos',
      },
      semester2: {
        gpa: 9.1,
        credits: 22,
        GPATerm: 'Média Semestral 2',
        creditsTerm: 'Créditos',
      },
    },
  },
  Spain: {
    code: 'ES',
    name: 'Spain',
    terms: {
      semesterGPA: 'Nota media',
      semesterCredits: 'Créditos ECTS',
      calculateCGPA: 'Calcular la nota media general',
      addSemester: 'Añadir semestre',
      deleteSemester: 'Eliminar semestre',
      placeholderGPA: 'Nota media {{n}}',
      placeholderCredits: 'Créditos {{n}}',
      resultCGPA: 'Nota media general',
      resultTotalSemesters: 'Total de semestres',
      resultTotalCredits: 'Total de Créditos',
    },
    example: {
      semester1: {
        gpa: 8.5,
        credits: '30/60',
        GPATerm: 'Nota media 1',
        creditsTerm: 'Créditos',
      },
      semester2: {
        gpa: 9.1,
        credits: '30/60',
        GPATerm: 'Nota media 2',
        creditsTerm: 'Créditos',
      },
    },
  },
  'United States': {
    code: 'US',
    name: 'United States',
    terms: {
      semesterGPA: 'Term GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 15,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.8,
        credits: 16,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },
  Canada: {
    code: 'CA',
    name: 'Canada',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credits / Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 15,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 3.8,
        credits: 18,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },
  Ghana: {
    code: 'GH',
    name: 'Ghana',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 15,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.8,
        credits: 16,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },
  Ethiopia: {
    code: 'ET',
    name: 'Ethiopia',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 16,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.8,
        credits: 18,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },
  Oman: {
    code: 'OM',
    name: 'Oman',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Hours',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Hours',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Hours',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: 15,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Hours',
      },
      semester2: {
        gpa: 3.8,
        credits: 16,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Hours',
      },
    },
  },
  Uganda: {
    code: 'UG',
    name: 'Uganda',
    terms: {
      semesterGPA: 'Semester GPA',
      semesterCredits: 'Credit Units',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credit Units',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Units',
    },
    example: {
      semester1: {
        gpa: 4.2,
        credits: 18,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Units',
      },
      semester2: {
        gpa: 4.5,
        credits: 20,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Units',
      },
    },
  },
  Russia: {
    code: 'RU',
    name: 'Russia',
    terms: {
      semesterGPA: 'Средний балл',
      semesterCredits: 'Зачётные единицы',
      calculateCGPA: 'Рассчитать средний балл',
      addSemester: 'Добавить семестр',
      deleteSemester: 'Удалить семестр',
      placeholderGPA: 'Средний балл {{n}}',
      placeholderCredits: 'Зачётные единицы {{n}}',
      resultCGPA: 'Ваш средний балл',
      resultTotalSemesters: 'Всего семестров',
      resultTotalCredits: 'Всего зачётных единиц',
    },
    example: {
      semester1: {
        gpa: 4.2,
        credits: 30,
        GPATerm: 'Средний балл 1',
        creditsTerm: 'Зачётные единицы',
      },
      semester2: {
        gpa: 4.8,
        credits: 30,
        GPATerm: 'Средний балл 2',
        creditsTerm: 'Зачётные единицы',
      },
    },
  },
  Portugal: {
    code: 'PT',
    name: 'Portugal',
    terms: {
      semesterGPA: 'Média Semestral',
      semesterCredits: 'Créditos ECTS',
      calculateCGPA: 'Calcular Média Final',
      addSemester: 'Adicionar Semestre',
      deleteSemester: 'Eliminar Semestre',
      placeholderGPA: 'Média Semestral {{n}}',
      placeholderCredits: 'Créditos ECTS {{n}}',
      resultCGPA: 'A sua Média Final',
      resultTotalSemesters: 'Total de Semestres',
      resultTotalCredits: 'Total de Créditos ECTS',
    },
    example: {
      semester1: {
        gpa: 14.5,
        credits: 30,
        GPATerm: 'Média Semestral 1',
        creditsTerm: 'Créditos ECTS',
      },
      semester2: {
        gpa: 16.2,
        credits: 30,
        GPATerm: 'Média Semestral 2',
        creditsTerm: 'Créditos ECTS',
      },
    },
  },
  Sweden: {
    code: 'SE',
    name: 'Sweden',
    terms: {
      semesterGPA: 'Medelbetyg (Average Grade)',
      semesterCredits: 'Högskolepoäng (Credits/HEC)',
      calculateCGPA: 'Beräkna totalt medelbetyg',
      addSemester: 'Lägg till termin',
      deleteSemester: 'Ta bort termin',
      placeholderGPA: 'Medelbetyg Termin {{n}}',
      placeholderCredits: 'Högskolepoäng Termin {{n}}',
      resultCGPA: 'Ditt totala medelbetyg',
      resultTotalSemesters: 'Totalt antal terminer',
      resultTotalCredits: 'Totalt antal högskolepoäng',
    },
    example: {
      semester1: {
        gpa: 4.5,
        credits: 30,
        GPATerm: 'Medelbetyg Termin 1',
        creditsTerm: 'Högskolepoäng',
      },
      semester2: {
        gpa: 4.8,
        credits: 30,
        GPATerm: 'Medelbetyg Termin 2',
        creditsTerm: 'Högskolepoäng',
      },
    },
  },
  Slovakia: {
    code: 'SK',
    name: 'Slovakia',
    terms: {
      semesterGPA: 'Semester Priemer',
      semesterCredits: 'Kredity (ECTS)',
      calculateCGPA: 'Vypočítať Celkový Priemer',
      addSemester: 'Pridať Semester',
      deleteSemester: 'Odstrániť Semester',
      placeholderGPA: 'Priemer Semestra {{n}}',
      placeholderCredits: 'Kredity Semestra {{n}}',
      resultCGPA: 'Váš Celkový Priemer',
      resultTotalSemesters: 'Celkový počet semestrov',
      resultTotalCredits: 'Celkový počet kreditov',
    },
    example: {
      semester1: {
        gpa: 1.5,
        credits: 30,
        GPATerm: 'Priemer Semestra 1',
        creditsTerm: 'Kredity',
      },
      semester2: {
        gpa: 1.2,
        credits: 30,
        GPATerm: 'Priemer Semestra 2',
        creditsTerm: 'Kredity',
      },
    },
  },
  Argentina: {
    code: 'AR',
    name: 'Argentina',
    terms: {
      semesterGPA: 'Promedio Semestral',
      semesterCredits: 'Créditos',
      calculateCGPA: 'Calcular Promedio General',
      addSemester: 'Añadir Semestre',
      deleteSemester: 'Eliminar Semestre',
      placeholderGPA: 'Promedio Semestral {{n}}',
      placeholderCredits: 'Créditos {{n}}',
      resultCGPA: 'Tu Promedio General',
      resultTotalSemesters: 'Total de Semestres',
      resultTotalCredits: 'Total de Créditos',
    },
    example: {
      semester1: {
        gpa: 8.0,
        credits: 20,
        GPATerm: 'Promedio Semestral 1',
        creditsTerm: 'Créditos',
      },
      semester2: {
        gpa: 9.2,
        credits: 22,
        GPATerm: 'Promedio Semestral 2',
        creditsTerm: 'Créditos',
      },
    },
  },
  Austria: {
    code: 'AT',
    name: 'Austria',
    terms: {
      semesterGPA: 'Semesterdurchschnitt',
      semesterCredits: 'ECTS-Punkte',
      calculateCGPA: 'Gesamtdurchschnitt berechnen',
      addSemester: 'Semester hinzufügen',
      deleteSemester: 'Semester löschen',
      placeholderGPA: 'Durchschnitt {{n}}',
      placeholderCredits: 'ECTS-Punkte {{n}}',
      resultCGPA: 'Ihr Gesamtdurchschnitt',
      resultTotalSemesters: 'Gesamtanzahl Semester',
      resultTotalCredits: 'Gesamt ECTS-Punkte',
    },
    example: {
      semester1: {
        gpa: 1.5,
        credits: '30/60',
        GPATerm: 'Durchschnitt Semester 1',
        creditsTerm: 'ECTS-Punkte',
      },
      semester2: {
        gpa: 1.2,
        credits: '30/60',
        GPATerm: 'Durchschnitt Semester 2',
        creditsTerm: 'ECTS-Punkte',
      },
    },
  },
  Belgium: {
    code: 'BE',
    name: 'Belgium',
    terms: {
      semesterGPA: 'Semestrieel Gemiddelde',
      semesterCredits: 'Studiepunten (ECTS)',
      calculateCGPA: 'Totaal Gemiddelde Berekenen',
      addSemester: 'Semester Toevoegen',
      deleteSemester: 'Semester Verwijderen',
      placeholderGPA: 'Gemiddelde Semester {{n}}',
      placeholderCredits: 'Studiepunten Semester {{n}}',
      resultCGPA: 'Uw Totaal Gemiddelde',
      resultTotalSemesters: 'Totaal Aantal Semesters',
      resultTotalCredits: 'Totaal Studiepunten',
    },
    example: {
      semester1: {
        gpa: 14.5,
        credits: '30/60',
        GPATerm: 'Gemiddelde Semester 1',
        creditsTerm: 'Studiepunten',
      },
      semester2: {
        gpa: 16.2,
        credits: '30/60',
        GPATerm: 'Gemiddelde Semester 2',
        creditsTerm: 'Studiepunten',
      },
    },
  },
  Denmark: {
    code: 'DK',
    name: 'Denmark',
    terms: {
      semesterGPA: 'Gennemsnitskarakter',
      semesterCredits: 'ECTS-points',
      calculateCGPA: 'Beregn Samlet Gennemsnit',
      addSemester: 'Tilføj Semester',
      deleteSemester: 'Slet Semester',
      placeholderGPA: 'Gennemsnit Semester {{n}}',
      placeholderCredits: 'ECTS-points Semester {{n}}',
      resultCGPA: 'Dit Samlede Gennemsnit',
      resultTotalSemesters: 'Total Antal Semestre',
      resultTotalCredits: 'Total ECTS-points',
    },
    example: {
      semester1: {
        gpa: 8.5,
        credits: 30,
        GPATerm: 'Gennemsnit Semester 1',
        creditsTerm: 'ECTS-points',
      },
      semester2: {
        gpa: 10.0,
        credits: 30,
        GPATerm: 'Gennemsnit Semester 2',
        creditsTerm: 'ECTS-points',
      },
    },
  },
  Finland: {
    code: 'FI',
    name: 'Finland',
    terms: {
      semesterGPA: 'Lukukauden Keskiarvo',
      semesterCredits: 'Opintopistettä (ECTS)',
      calculateCGPA: 'Laske Koko Keskiarvo',
      addSemester: 'Lisää Lukukausi',
      deleteSemester: 'Poista Lukukausi',
      placeholderGPA: 'Keskiarvo Lukukausi {{n}}',
      placeholderCredits: 'Opintopistettä Lukukausi {{n}}',
      resultCGPA: 'Koko Keskiarvo',
      resultTotalSemesters: 'Lukukausien Kokonaismäärä',
      resultTotalCredits: 'Opintopisteiden Kokonaismäärä',
    },
    example: {
      semester1: {
        gpa: 4.2,
        credits: '30/60',
        GPATerm: 'Keskiarvo Lukukausi 1',
        creditsTerm: 'Opintopistettä',
      },
      semester2: {
        gpa: 4.8,
        credits: '30/60',
        GPATerm: 'Keskiarvo Lukukausi 2',
        creditsTerm: 'Opintopistettä',
      },
    },
  },
  Greece: {
    code: 'GR',
    name: 'Greece',
    terms: {
      semesterGPA: 'Μέσος Όρος Εξαμήνου',
      semesterCredits: 'Πιστωτικές Μονάδες (ECTS)',
      calculateCGPA: 'Υπολογισμός Γενικού Μέσου Όρου',
      addSemester: 'Προσθήκη Εξαμήνου',
      deleteSemester: 'Διαγραφή Εξαμήνου',
      placeholderGPA: 'Μέσος Όρος Εξαμήνου {{n}}',
      placeholderCredits: 'Πιστωτικές Μονάδες Εξαμήνου {{n}}',
      resultCGPA: 'Ο Γενικός σας Μέσος Όρος',
      resultTotalSemesters: 'Σύνολο Εξαμήνων',
      resultTotalCredits: 'Σύνολο Πιστωτικών Μονάδων',
    },
    example: {
      semester1: {
        gpa: 6.8,
        credits: '30/60',
        GPATerm: 'Μέσος Όρος Εξαμήνου 1',
        creditsTerm: 'Πιστωτικές Μονάδες',
      },
      semester2: {
        gpa: 8.5,
        credits: '30/60',
        GPATerm: 'Μέσος Όρος Εξαμήνου 2',
        creditsTerm: 'Πιστωτικές Μονάδες',
      },
    },
  },
  Lithuania: {
    code: 'LT',
    name: 'Lithuania',
    terms: {
      semesterGPA: 'Semestro Vidurkis',
      semesterCredits: 'Kreditai (ECTS)',
      calculateCGPA: 'Apskaičiuoti Bendrą Vidurkį',
      addSemester: 'Pridėti Semestrą',
      deleteSemester: 'Ištrinti Semestrą',
      placeholderGPA: 'Vidurkis Semestras {{n}}',
      placeholderCredits: 'Kreditai Semestras {{n}}',
      resultCGPA: 'Jūsų Bendras Vidurkis',
      resultTotalSemesters: 'Viso Semestrų',
      resultTotalCredits: 'Viso Kreditų',
    },
    example: {
      semester1: {
        gpa: 8.5,
        credits: '30/60',
        GPATerm: 'Vidurkis Semestras 1',
        creditsTerm: 'Kreditai',
      },
      semester2: {
        gpa: 9.1,
        credits: '30/60',
        GPATerm: 'Vidurkis Semestras 2',
        creditsTerm: 'Kreditai',
      },
    },
  },
  Norway: {
    code: 'NO',
    name: 'Norway',
    terms: {
      semesterGPA: 'Semester Gjennomsnitt (A=5.0, E=1.0)',
      semesterCredits: 'Studiepoeng (ECTS)',
      calculateCGPA: 'Beregn Samlet Gjennomsnitt',
      addSemester: 'Legg til Semester',
      deleteSemester: 'Slett Semester',
      placeholderGPA: 'Gjennomsnitt Semester {{n}}',
      placeholderCredits: 'Studiepoeng Semester {{n}}',
      resultCGPA: 'Ditt Samlede Gjennomsnitt',
      resultTotalSemesters: 'Totalt Antall Semestre',
      resultTotalCredits: 'Totalt Studiepoeng',
    },
    example: {
      semester1: {
        gpa: 4.2,
        credits: '30/60',
        GPATerm: 'Gjennomsnitt Semester 1',
        creditsTerm: 'Studiepoeng',
      },
      semester2: {
        gpa: 3.8,
        credits: '30/60',
        GPATerm: 'Gjennomsnitt Semester 2',
        creditsTerm: 'Studiepoeng',
      },
    },
  },
  Georgia: {
    code: 'GE',
    name: 'Georgia',
    terms: {
      semesterGPA: 'Semester GPA ',
      semesterCredits: 'Credits / ECTS',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Semester {{n}} Credits',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credits',
    },
    example: {
      semester1: {
        gpa: 3.5,
        credits: '30/60',
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credits',
      },
      semester2: {
        gpa: 3.8,
        credits: '30/60',
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credits',
      },
    },
  },
  Botswana: {
    code: 'BW',
    name: 'Botswana',
    terms: {
      semesterGPA: 'Semester GPA ',
      semesterCredits: 'Credit Units',
      calculateCGPA: 'Calculate CGPA',
      addSemester: 'Add Semester',
      deleteSemester: 'Delete Semester',
      placeholderGPA: 'Semester {{n}} GPA',
      placeholderCredits: 'Credit Units {{n}}',
      resultCGPA: 'Your CGPA Result',
      resultTotalSemesters: 'Total Semesters',
      resultTotalCredits: 'Total Credit Units',
    },
    example: {
      semester1: {
        gpa: 3.9,
        credits: 16,
        GPATerm: 'Semester 1 GPA',
        creditsTerm: 'Credit Units',
      },
      semester2: {
        gpa: 3.7,
        credits: 18,
        GPATerm: 'Semester 2 GPA',
        creditsTerm: 'Credit Units',
      },
    },
  },
  Chile: {
    code: 'CL',
    name: 'Chile',
    terms: {
      semesterGPA: 'Promedio Semestral',
      semesterCredits: 'Créditos',
      calculateCGPA: 'Calcular Promedio Ponderado Acumulado (PPA)',
      addSemester: 'Añadir Semestre',
      deleteSemester: 'Eliminar Semestre',
      placeholderGPA: 'Promedio Semestral {{n}}',
      placeholderCredits: 'Créditos {{n}}',
      resultCGPA: 'Su PPA (Promedio General)',
      resultTotalSemesters: 'Total de Semestres',
      resultTotalCredits: 'Total de Créditos',
    },
    example: {
      semester1: {
        gpa: 5.5,
        credits: 30,
        GPATerm: 'Promedio Semestral 1',
        creditsTerm: 'Créditos',
      },
      semester2: {
        gpa: 6.2,
        credits: 30,
        GPATerm: 'Promedio Semestral 2',
        creditsTerm: 'Créditos',
      },
    },
  },
  Mexico: {
    code: 'MX',
    name: 'Mexico',
    terms: {
      semesterGPA: 'Promedio Semestral',
      semesterCredits: 'Créditos',
      calculateCGPA: 'Calcular Promedio Acumulado',
      addSemester: 'Añadir Semestre',
      deleteSemester: 'Eliminar Semestre',
      placeholderGPA: 'Promedio Semestral {{n}}',
      placeholderCredits: 'Créditos {{n}}',
      resultCGPA: 'Su Promedio General',
      resultTotalSemesters: 'Total de Semestres',
      resultTotalCredits: 'Total de Créditos',
    },
    example: {
      semester1: {
        gpa: 8.5,
        credits: 25,
        GPATerm: 'Promedio Semestral 1',
        creditsTerm: 'Créditos',
      },
      semester2: {
        gpa: 9.2,
        credits: 24,
        GPATerm: 'Promedio Semestral 2',
        creditsTerm: 'Créditos',
      },
    },
  },
  Colombia: {
    code: 'CO',
    name: 'Colombia',
    terms: {
      semesterGPA: 'Promedio Semestral',
      semesterCredits: 'Créditos Académicos',
      calculateCGPA: 'Calcular Promedio Ponderado Acumulado (PPA)',
      addSemester: 'Añadir Semestre',
      deleteSemester: 'Eliminar Semestre',
      placeholderGPA: 'Promedio Semestral {{n}}',
      placeholderCredits: 'Créditos Académicos {{n}}',
      resultCGPA: 'Su PPA (Promedio General)',
      resultTotalSemesters: 'Total de Semestres',
      resultTotalCredits: 'Total de Créditos Académicos',
    },
    example: {
      semester1: {
        gpa: 4.1,
        credits: 16,
        GPATerm: 'Promedio Semestral 1',
        creditsTerm: 'Créditos Académicos',
      },
      semester2: {
        gpa: 4.5,
        credits: 18,
        GPATerm: 'Promedio Semestral 2',
        creditsTerm: 'Créditos Académicos',
      },
    },
  },
};
